---
title: "daily movement metrics"
author: "David"
date: "11/30/2020"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(scipen=999)
```

```{r import packages}
library(tidyverse)
library(overlap)
library(circular)
library(CircStats)
library(adehabitatLT)
library(sp)
library(here)
library(lubridate)
```

Import data. I'll just use a couple pigs to work out the methods, then scale up to the full dataset.
```{r import data and format}
df<-read.csv(here("data/BIRSpringGPS.csv"))
df<-df %>% filter(Indiv_ID=="F11"|Indiv_ID=="M8")

df$Fix_DateTime<-as.character(df$Fix_DateTime)
df$Fix_DateTime<-as.POSIXct(strptime(df$Fix_DateTime,
                            "%Y/%m/%d %H:%M",
                            tz="America/New_York"))
```

Pull off necessary info from gps data
```{r}
df_traj<-as.ltraj(xy = df[,c("X","Y")], date=df$Fix_DateTime,
                  id = df$Indiv_ID, typeII=TRUE,
                  burst = df$Indiv_ID)
df_ld<-ld(df_traj)
df<-as_tibble(df_ld)

df<-df %>% 
  mutate(dtmin=dt/60,       #creates a new column for amount of time between points in minutes
         dthr=dt/3600,      #creates a new column for time between points in hours
         meterph=round(dist/dthr, digits=0))%>% #calculates movement rate in meters per hour
  dplyr::select(x, y, date, dist,dt, dtmin, dthr, meterph, id)
```

Function for making psuedo-observations
```{r}
gen_rand_times.mod <- function(N, st, et, id) {
  dt <- as.numeric(difftime(et, st, unit="sec")) #calculates the interval in seconds between the start time and end time of the interval
  ev <- sort(runif(N, 0, dt)) #generates N random values within that interval and sorts them from least to greatest
  rt <- st + ev
  } # adds the generate times in seconds to the start value to create a vector of times between the start and the end

```

Calculate pseudo-observations
```{r}
results <- list() #sets up list for storing results
for(i in 1:nrow(df)){
  if(df$dtmin[i]>19 & df$dtmin[i]<41 & is.na(df$dtmin[i])==FALSE){
    results[[i]]<-gen_rand_times.mod(N = df$meterph[i], 
                                     st = df$date[i], 
                                     et = df$date[i+1])
  }
}

# Convert from list to dataframe
rand_df<-plyr::ldply(results, data.frame)
rand_df<-rand_df %>%
  rename(datetime="X..i..") %>% 
  mutate(Indiv_ID = rep("data", times=nrow(rand_df)),
         time=format(ymd_hms(datetime), "%H:%M:%S"))

rand_df<-rand_df %>% 
  mutate(fractime=hms(time)/hms("24:00:00"),
         timeRad=fractime*2*pi)
```


